---
- hosts: 127.0.0.1
  become: yes
  tasks:
   - name: create k8 cluster of 3 nodes
     command:
             eksctl create cluster
             --name capstone
             --region eu-central-1
             --nodegroup-name workers
             --node-type t2.small
             --nodes 3
             --nodes-min 2
             --nodes-max 4

